import { Product, Farmer, Supplier, Category, Testimonial, Story, VerificationStep } from './types';
import { IMAGES } from './images';

export const CATEGORIES_DATA: Category[] = [
  {
    id: 'cat-veg',
    name: 'Vegetables',
    slug: 'vegetables',
    description: 'Crisp, nutrient-rich farm greens and vegetables harvested daily.',
    image: IMAGES.categories.vegetables.url,
    itemCount: 42,
    icon: 'Carrot',
  },
  {
    id: 'cat-fruits',
    name: 'Fruits',
    slug: 'fruits',
    description: 'Tree-ripened regional fruits picked at optimal sweetness.',
    image: IMAGES.categories.fruits.url,
    itemCount: 28,
    icon: 'Apple',
  },
  {
    id: 'cat-grains',
    name: 'Grains & Millets',
    slug: 'grains',
    description: 'Heritage unpolished rice, indigenous millets, and whole grains.',
    image: IMAGES.categories.grains.url,
    itemCount: 35,
    icon: 'Wheat',
  },
  {
    id: 'cat-pulses',
    name: 'Pulses & Lentils',
    slug: 'pulses',
    description: 'Sun-dried protein-rich lentils, chickpeas, and dals.',
    image: IMAGES.categories.pulses.url,
    itemCount: 24,
    icon: 'Bean',
  },
  {
    id: 'cat-organic',
    name: 'Organic Specials',
    slug: 'organic',
    description: 'Certified chemical-free and zero-budget natural farm harvest.',
    image: IMAGES.categories.organic.url,
    itemCount: 50,
    icon: 'Sparkles',
  },
  {
    id: 'cat-seeds',
    name: 'Native Seeds',
    slug: 'seeds',
    description: 'Heirloom, high-germination non-hybrid seed collections.',
    image: IMAGES.categories.seeds.url,
    itemCount: 19,
    icon: 'Sprout',
  },
  {
    id: 'cat-dairy',
    name: 'Farm Dairy',
    slug: 'dairy',
    description: 'Desi A2 milk, cultured bilona ghee, and fresh dairy staples.',
    image: IMAGES.categories.dairy.url,
    itemCount: 16,
    icon: 'Milk',
  },
  {
    id: 'cat-supplies',
    name: 'Farm Supplies',
    slug: 'supplies',
    description: 'Irrigation kits, bio-fertilizers, solar gear, and implements.',
    image: IMAGES.categories.supplies.url,
    itemCount: 31,
    icon: 'Wrench',
  },
];

export const PRODUCTS_DATA: Product[] = [
  {
    id: 'prod-1',
    name: 'Organic Vine Tomatoes',
    category: 'Vegetables',
    price: 60,
    originalPrice: 75,
    unit: 'kg',
    farmerName: 'Green Valley Farm',
    farmerId: 'farmer-1',
    location: 'Telangana',
    rating: 4.9,
    reviewsCount: 84,
    image: IMAGES.products.tomatoes.url,
    freshness: 'Harvested 4 hrs ago',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'Naturally grown country tomatoes ripened on the vine without chemical accelerators. Sweet, juicy, and rich in lycopene.',
    harvestDate: 'Today, 5:30 AM',
    minimumOrder: '2 kg',
    nutritionalHighlight: 'Rich in Vitamin C & Lycopene',
  },
  {
    id: 'prod-2',
    name: 'Desi Sweet Red Carrots',
    category: 'Vegetables',
    price: 45,
    originalPrice: 55,
    unit: 'kg',
    farmerName: 'Krishna Natural Farms',
    farmerId: 'farmer-2',
    location: 'Andhra Pradesh',
    rating: 4.8,
    reviewsCount: 62,
    image: IMAGES.products.carrots.url,
    freshness: 'Harvested yesterday',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'Crisp indigenous red carrots grown in sandy loam soil with traditional compost. Excellent natural sweetness for juices and salads.',
    harvestDate: 'Yesterday morning',
    minimumOrder: '1 kg',
    nutritionalHighlight: 'High Beta-Carotene & Dietary Fiber',
  },
  {
    id: 'prod-3',
    name: 'Aged Sona Masoori Raw Rice',
    category: 'Grains & Millets',
    price: 85,
    originalPrice: 98,
    unit: 'kg',
    farmerName: 'Godavari Paddy Collective',
    farmerId: 'farmer-3',
    location: 'Andhra Pradesh',
    rating: 4.9,
    reviewsCount: 110,
    image: IMAGES.products.rice.url,
    freshness: 'Single-source lot 2026',
    verified: true,
    certified: true,
    inStock: true,
    organic: false,
    description: 'Aromatic, single-origin medium grain rice aged naturally for 12 months for fluffier cooking and lightweight digestion.',
    harvestDate: 'December 2025 harvest',
    minimumOrder: '5 kg',
    nutritionalHighlight: 'Low glycemic index aged rice',
  },
  {
    id: 'prod-4',
    name: 'Fresh Country Palak (Spinach)',
    category: 'Vegetables',
    price: 25,
    originalPrice: 30,
    unit: 'bunch',
    farmerName: 'Medak Green Acres',
    farmerId: 'farmer-1',
    location: 'Telangana',
    rating: 4.7,
    reviewsCount: 43,
    image: IMAGES.products.spinach.url,
    freshness: 'Harvested 3 hrs ago',
    verified: true,
    certified: false,
    inStock: true,
    organic: true,
    description: 'Tender broad-leaf spinach watered with fresh borewell water and enriched with jeevamrutham fertilizer.',
    harvestDate: 'Today, 6:00 AM',
    minimumOrder: '2 bunches',
    nutritionalHighlight: 'High Iron, Folate & Chlorophyll',
  },
  {
    id: 'prod-5',
    name: 'Banganapalle Mangoes (Naturally Ripened)',
    category: 'Fruits',
    price: 160,
    originalPrice: 190,
    unit: 'kg',
    farmerName: 'Rayalaseema Orchards',
    farmerId: 'farmer-4',
    location: 'Andhra Pradesh',
    rating: 5.0,
    reviewsCount: 154,
    image: IMAGES.products.mangoes.url,
    freshness: 'Seasonal Fresh Crop',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'Famous Andhra GI-style Banganapalle mangoes straw-ripened without calcium carbide. Thin skin and rich floral aroma.',
    harvestDate: 'Hand-plucked 2 days ago',
    minimumOrder: '3 kg crate',
    nutritionalHighlight: 'Zero synthetic ripening chemicals',
  },
  {
    id: 'prod-6',
    name: 'Raw Unfiltered Forest Honey',
    category: 'Organic Specials',
    price: 340,
    originalPrice: 390,
    unit: '500g jar',
    farmerName: 'Nallamala Tribal Producers',
    farmerId: 'farmer-5',
    location: 'Telangana',
    rating: 4.9,
    reviewsCount: 97,
    image: IMAGES.products.honey.url,
    freshness: 'Cold-extracted batch',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'Wild multi-flora honey harvested sustainably by forest community gatherers. Unpasteurized and replete with active pollen.',
    harvestDate: 'Extracted this month',
    minimumOrder: '1 jar',
    nutritionalHighlight: 'High enzymes & active bee pollen',
  },
  {
    id: 'prod-7',
    name: 'Sun-Dried Guntur Red Chili',
    category: 'Pulses & Lentils',
    price: 190,
    originalPrice: 220,
    unit: 'kg',
    farmerName: 'Palnadu Spices Farm',
    farmerId: 'farmer-6',
    location: 'Andhra Pradesh',
    rating: 4.8,
    reviewsCount: 51,
    image: IMAGES.products.chili.url,
    freshness: 'Sun-cured batch',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'High-pungency, vibrant red Guntur Sannam chilies dried on clean elevated tarpaulins under the Deccan sun.',
    harvestDate: 'Direct farm sun-dried',
    minimumOrder: '1 kg',
    nutritionalHighlight: 'Zero artificial dye or mineral oil',
  },
  {
    id: 'prod-8',
    name: 'Curcumin-Rich Lakadong Turmeric',
    category: 'Organic Specials',
    price: 220,
    originalPrice: 260,
    unit: '250g pack',
    farmerName: 'Eastern Ghats Organics',
    farmerId: 'farmer-7',
    location: 'Andhra Pradesh',
    rating: 4.9,
    reviewsCount: 78,
    image: IMAGES.products.turmeric.url,
    freshness: 'Stone-milled fresh',
    verified: true,
    certified: true,
    inStock: true,
    organic: true,
    description: 'Exceptional aromatic turmeric tested at 7%+ natural curcumin content. Hand-sorted rhizomes, gently sun-dried and ground.',
    harvestDate: 'Fresh harvest lot',
    minimumOrder: '1 pack',
    nutritionalHighlight: '7.2% Lab-Tested Curcumin',
  },
  {
    id: 'prod-9',
    name: 'Micro-Drip Irrigation 1-Acre Kit',
    category: 'Farm Supplies',
    price: 4800,
    originalPrice: 5500,
    unit: 'kit',
    farmerName: 'Varun Agri Solutions',
    farmerId: 'supplier-1',
    location: 'Telangana',
    rating: 4.9,
    reviewsCount: 38,
    image: IMAGES.products.dripKit.url,
    freshness: 'Factory Sealed with 3yr Warranty',
    verified: true,
    certified: true,
    inStock: true,
    organic: false,
    description: 'Complete gravity-compatible micro-drip layout kit with 16mm inline lateral tubes, disc filter, punch tools, and flush valves.',
    harvestDate: 'Manufacturer certified 2026',
    minimumOrder: '1 kit',
    nutritionalHighlight: 'Conserves 65% water vs flood irrigation',
  },
];

export const FEATURED_FARMER: Farmer = {
  id: 'farmer-1',
  name: 'Ramesh Kumar',
  specialty: 'Organic Vegetables & Horticulture',
  location: 'Medak',
  state: 'Telangana',
  rating: 4.9,
  reviewsCount: 142,
  productsSoldCount: 128,
  image: IMAGES.farmers.ramesh.url,
  verified: true,
  bio: 'Second-generation grower practicing natural chemical-free farming across 8 acres. Certified pesticide-free with verified direct consumer supply.',
  experienceYears: 16,
  acresCultivated: 8,
  primaryCrops: ['Vine Tomatoes', 'Country Greens', 'Desi Cucumbers', 'Okra'],
  whatsappPhone: '+91 98765 43210',
};

export const OTHER_FARMERS: Farmer[] = [
  {
    id: 'farmer-2',
    name: 'Lakshmi Devi',
    specialty: 'Natural Horticulture & Heirloom Melons',
    location: 'Warangal',
    state: 'Telangana',
    rating: 4.9,
    reviewsCount: 96,
    productsSoldCount: 85,
    image: IMAGES.farmers.lakshmi.url,
    verified: true,
    bio: 'Pioneer woman farmer practicing zero-budget natural farming with native bio-inputs and multi-cropping.',
    experienceYears: 12,
    acresCultivated: 5,
    primaryCrops: ['Red Carrots', 'Watermelons', 'Country Brinjal'],
    whatsappPhone: '+91 98765 43211',
  },
  {
    id: 'farmer-3',
    name: 'Venkat Rao',
    specialty: 'Indigenous Grains & Rainfed Millets',
    location: 'Nizamabad',
    state: 'Telangana',
    rating: 4.8,
    reviewsCount: 88,
    productsSoldCount: 112,
    image: IMAGES.farmers.venkat.url,
    verified: true,
    bio: 'Conserving heirloom drought-hardy millet cultivars and traditional single-origin paddy varieties.',
    experienceYears: 22,
    acresCultivated: 14,
    primaryCrops: ['Sona Masoori Rice', 'Foxtail Millet', 'Pearl Millet'],
    whatsappPhone: '+91 98765 43212',
  },
];

export const SUPPLIERS_DATA: Supplier[] = [
  {
    id: 'supplier-1',
    name: 'Varun Agri Solutions',
    category: 'Irrigation & Solar Systems',
    location: 'Hyderabad',
    state: 'Telangana',
    rating: 4.9,
    productsCount: 24,
    image: IMAGES.suppliers.irrigation.url,
    verified: true,
    description: 'High-efficiency gravity drip equipment, solar water pumps, and pressure-compensating emitters for small and medium farms.',
    specialties: ['Drip Irrigation', 'Solar Pumps', 'Fertigation Venturis'],
  },
  {
    id: 'supplier-2',
    name: 'Annapurna Native Seeds',
    category: 'Certified Native Seeds',
    location: 'Warangal',
    state: 'Telangana',
    rating: 4.8,
    productsCount: 38,
    image: IMAGES.suppliers.seeds.url,
    verified: true,
    description: 'Tested heirloom non-hybrid crop seeds with 90%+ germination rate, acclimatized to southern dry-zone weather.',
    specialties: ['Heritage Paddy Seeds', 'Millet Seeds', 'Vegetable Kits'],
  },
  {
    id: 'supplier-3',
    name: 'BioKisan Eco Inputs',
    category: 'Bio-Fertilizers & Pest Control',
    location: 'Vijayawada',
    state: 'Andhra Pradesh',
    rating: 4.9,
    productsCount: 19,
    image: IMAGES.suppliers.bioFertilizer.url,
    verified: true,
    description: 'Enriched vermicompost, Trichoderma soil inoculants, neem cake, and bio-culture formulations for regenerative growers.',
    specialties: ['Vermicompost', 'Neem Oil 10,000ppm', 'Pseudomonas'],
  },
  {
    id: 'supplier-4',
    name: 'Deccan Implement Works',
    category: 'Farm Tools & Machinery',
    location: 'Karimnagar',
    state: 'Telangana',
    rating: 4.7,
    productsCount: 15,
    image: IMAGES.suppliers.equipment.url,
    verified: true,
    description: 'Ergonomic manual weeders, battery-assisted knapsack sprayers, and lightweight rotary tillers built for Indian conditions.',
    specialties: ['Battery Sprayers', 'Cono Weeders', 'Seed Drills'],
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Ramesh Kumar',
    role: 'Farmer',
    location: 'Medak, Telangana',
    avatar: IMAGES.farmers.ramesh.url,
    quote: 'Before Rythu Nestham, we depended on distant mandi middlemen who delayed payments for weeks. Now, verified consumers order directly and payments reach me transparently. It has transformed my farm stability.',
    rating: 5,
    tag: 'Sold 128 Products Directly',
    verified: true,
  },
  {
    id: 'test-2',
    name: 'Ananya Sharma',
    role: 'Consumer',
    location: 'Hyderabad, Telangana',
    avatar: IMAGES.farmers.ananya.url,
    quote: 'Finding genuinely chemical-free vegetables in the city used to be a guessing game. Rythu Nestham gives full farm origin and inspection proof. The tomatoes smell like real farm vegetables from my childhood.',
    rating: 5,
    tag: 'Weekly Subscriber',
    verified: true,
  },
  {
    id: 'test-3',
    name: 'Kiran Patel',
    role: 'Supplier',
    location: 'Hyderabad, Telangana',
    avatar: IMAGES.farmers.kiran.url,
    quote: 'Supplying micro-drip kits to progressive farmers across Telangana became straightforward through Rythu Nestham. Farmers see the specs and can chat with us directly via WhatsApp to configure their acreage.',
    rating: 5,
    tag: 'Verified Equipment Partner',
    verified: true,
  },
  {
    id: 'test-4',
    name: 'Lakshmi Devi',
    role: 'Farmer',
    location: 'Warangal, Telangana',
    avatar: IMAGES.farmers.lakshmi.url,
    quote: 'Getting our natural farming harvest certified and listed without bureaucratic hurdles gave our women farmer collective the confidence to expand production by two more acres.',
    rating: 5,
    tag: 'Women Farmer Collective Lead',
    verified: true,
  },
];

export const STORIES_DATA: Story[] = [
  {
    id: 'story-1',
    title: 'Reviving Drought-Resilient Millets in the Deccan Plateau',
    category: 'Farming Insights',
    summary: 'How dryland farmers in Nizamabad are restoring foxtail and pearl millets to conserve 70% groundwater while producing nutrient-dense crops.',
    readTime: '4 min read',
    date: 'Sep 2026',
    image: IMAGES.editorial.millets.url,
    author: 'K. Venkat Rao',
  },
  {
    id: 'story-2',
    title: 'From Soil to Health: Understanding Natural Farm Verification',
    category: 'Transparency',
    summary: 'A deep dive into how Rythu Nestham audits soil health, water sources, and pesticide residues before giving any listing our verified badge.',
    readTime: '5 min read',
    date: 'Aug 2026',
    image: IMAGES.editorial.soilHealth.url,
    author: 'Dr. Radhika Chenna',
  },
  {
    id: 'story-3',
    title: 'Micro-Irrigation Wisdom for Smallholder Farmland',
    category: 'Agricultural Tips',
    summary: 'Practical guidance on laying gravity-fed drip networks on half-acre plots without heavy diesel pump electricity expenditures.',
    readTime: '6 min read',
    date: 'Jul 2026',
    image: IMAGES.editorial.waterWisdom.url,
    author: 'Varun Agri Solutions',
  },
];

export const VERIFICATION_STEPS: VerificationStep[] = [
  {
    id: 1,
    stage: 'Stage 01',
    title: 'Submitted',
    description: 'Farmer or supplier submits crop harvest details, farm location GPS, and batch photos through the portal.',
    proofType: 'Harvest Lot Registration',
    iconName: 'FileCheck',
  },
  {
    id: 2,
    stage: 'Stage 02',
    title: 'Inspected',
    description: 'Field agronomist or cluster coordinator inspects crop cultivation history, soil inputs, and water sources.',
    proofType: 'On-Ground Physical Audit',
    iconName: 'SearchCheck',
  },
  {
    id: 3,
    stage: 'Stage 03',
    title: 'Verified',
    description: 'Grower identity, land records, and non-toxic agricultural practice compliance are cross-verified.',
    proofType: 'Grower Identity & Compliance',
    iconName: 'UserCheck',
  },
  {
    id: 4,
    stage: 'Stage 04',
    title: 'Certified',
    description: 'A tamper-proof digital quality badge and batch QR record is generated for transparency.',
    proofType: 'Digital Badge Issuance',
    iconName: 'Award',
  },
  {
    id: 5,
    stage: 'Stage 05',
    title: 'Listed',
    description: 'Produce goes live on the marketplace where conscious consumers and bulk buyers can purchase with confidence.',
    proofType: 'Marketplace Live Showcase',
    iconName: 'ShoppingBag',
  },
];

export const IMPACT_STATS = [
  {
    value: '1,200+',
    label: 'Farmers Connected',
    subtext: 'Across rural districts',
    icon: 'Users',
  },
  {
    value: '450+',
    label: 'Verified Listings',
    subtext: 'Fresh crops & farm supplies',
    icon: 'CheckCircle',
  },
  {
    value: '28+',
    label: 'Rural Mandals',
    subtext: 'Direct logistics clusters',
    icon: 'MapPin',
  },
  {
    value: '100%',
    label: 'Checked Listings',
    subtext: 'Audit before live listing',
    icon: 'ShieldCheck',
  },
];
